Repository terraform-providers/terraform-provider-profitbricks, pull requests merged in 2019-01, with the labels that each got.

#43 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
  profitbricks/import_profitbricks_datacenter_test.go
  profitbricks/import_profitbricks_firewall_test.go
  profitbricks/import_profitbricks_ipblock_test.go
  profitbricks/import_profitbricks_lan_test.go
  profitbricks/import_profitbricks_nic_test.go
  profitbricks/import_profitbricks_server_test.go
  profitbricks/resource_profitbricks_ipfailover.go
  profitbricks/resource_profitbricks_loadbalancer.go
Labels: size/S

#44 Client token auth
  profitbricks/config.go
  profitbricks/provider.go
  profitbricks/provider_test.go
  vendor/github.com/profitbricks/profitbricks-sdk-go/README.md
  vendor/github.com/profitbricks/profitbricks-sdk-go/image.go
  vendor/github.com/profitbricks/profitbricks-sdk-go/profitbricks.go
  vendor/github.com/profitbricks/profitbricks-sdk-go/req.go
  vendor/vendor.json
Labels: dependencies, size/M

#45 Fetch datacenter resource by id
  go.mod
  go.sum
  profitbricks/data_source_datacenter.go
Labels: dependencies, size/L
